name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "make slides"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: _build/html/