name: Build and publish docs to GH Pages

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Sphinx
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "make slides"
    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ GIT_BRANCH_NAME == 'main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/slides/
    - name: Deploy branch to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ GIT_BRANCH_NAME != 'main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/slides/
        destination_dir: ./${GIT_BRANCH_NAME}